theme: jekyll-theme-cayman
title: Niels Justesen
description: AI researcher at modl.ai
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  parse_block_html: true
include:
  - index.md